### ISSUE TITLE
ExpandTabs set Off

### ISSUE THREAD

**Issue by ViViDboarder** [ejholmes/vim-forcedotcom#2]
For some reason when doing `set filetype=apex` it turns off expandtabs for me. I normally have my tabs set to expanded 4 spaces but found recently that all my apex files now have `^I` chars in them.

If I open any normal text file I can indent with spaces just fine, but then executing  `set filetype=apex` switches me to tabs while  `set filetype=java` allows me to keep spaces.

I looked through your plugin but I can't seem to find anything that stands out as a culprit.

**Comment by skeletal** [comment]
I've encountered exactly the same issue with this plugin, could you please provide some detail to your solution in case it's the same issue I am having? (if you remember from 4 years ago)

**Comment by ViViDboarder** [comment]
I can't remember... sorry. I checked my vim-settings history but no luck there either.

What I think was that I had been using something like [this](http://www.vim.org/scripts/script.php?script_id=4550), and it caused problems.

It shouldn't be necessary anymore since vim should have better support for it, though I'm not sure. That's where I'd look though! You can try to run `:autocmd` and see if anything there might be adjusting intents.
